# docker-compose.yml - Application services (can be restarted safely)
services:
  localai-api:
    build:
      context: .  # Changed: Use root as context
      dockerfile: src/LocalAI.Api/Dockerfile  # Changed: Full path to Dockerfile
    container_name: localai-api
    ports:
      - "7190:8080"
    environment:
      # Connect to external Qdrant service
      - QdrantSettings__Endpoint=http://qdrant-persistent:6333
      - LMStudioSettings__Endpoint=http://host.docker.internal:1234
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
      - ./data:/app/data:ro
    restart: unless-stopped
    networks:
      - localai-network
      
  localai-web:
    build:
      context: .  # Changed: Use root as context
      dockerfile: src/LocalAI.Web/Dockerfile  # Changed: Full path to Dockerfile
    container_name: localai-web
    ports:
      - "7001:8080"
    environment:
      - ApiSettings__BaseUrl=http://localai-api:8080
    depends_on:
      - localai-api
    restart: unless-stopped
    networks:
      - localai-network

# Use external network created by infrastructure
networks:
  localai-network:
    external: true