# docker-compose.infrastructure.yml - Persistent services that stay up
version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-persistent
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      # Persistent data storage
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    # Resource limits for your RTX 5070 Ti system
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    networks:
      - localai-network

# Shared network for both compose files
networks:
  localai-network:
    external: true

volumes:
  qdrant_data:
    driver: local